### PR TITLE
Update workflows to DSL2

### LINKED ISSUE #23: Port the patterns to DSL2
I noticed that the patterns are (i) still in the DSL1 and (ii) use deprecated features like `set` value and (iii) do not make use of the newer helpful features such as `stub` for quick iterations. Perhaps, it might be beneficial for the overall community to move the patterns to DSL2 to facilitate the transition. 

What do you think?

### PR DESCRIPTION
**Pull request by bentsherman**
Resolves #23 

This PR updates all workflow patterns to DSL2.

Notes:
- I kept the channel duplication pattern just to show that `into` is no longer needed in DSL2
- Renamed "mock dependency" to "state dependency" for clarity, "mock" suggests something related to unit testing or dry run
- I tended to use syntax shortcuts like `|` and `&` as much as possible, let me know if I went overboard or could do more in any examples

TODO:
- [x] Update docs files with new examples

### CODE REVIEW

**Comment by pditommaso** [comment]
This is great! however I've tried a couple and there are not working. e.g 

```
process foo {
  errorStrategy 'ignore'
  script:
  '''
  echo This is going to fail!
  exit 1
  '''
}

process bar {
  script:
  '''
  echo OK
  '''
}

workflow {
  foo & bar
}
```

and


```
process foo {
  publishDir 'results', saveAs: { filename -> filename.endsWith(".zip") ? "zips/$filename" : filename }

  output:
  path '*'

  '''
  touch this.txt
  touch that.zip
  '''
}

workflow {
  foo
}
```


Broken docs is much worse than not having docs. Those should be tested one by one before merging.

**Comment by bentsherman** [comment]
Okay it looks like I was misunderstanding the DSL2 syntax here. I assumed that
```
workflow {
  foo
}
```
would simply call `foo`, but it looks like you have to explicitly invoke `foo()`, and `foo` by itself is only valid when using pipes. I will review and correct my changes accordingly.

**Comment by bentsherman** [comment]
The reason I didn't catch these problems is because the syntax is still valid, the workflow doesn't fail but simply runs nothing and exits. Might warrant some clarification in the Nextflow docs.

**Comment by bentsherman** [comment]
Okay I made the changes you requested 👍

**Comment by pditommaso** [comment]
This is wrong 

```
process foo {
  echo true
  input:
  file x

  script:
  """
  echo your_command --input $x
  """
}

workflow {
  foo("$baseDir/data/reads/*_1.fq.gz")
}
```

because the input is declared as `file` and the concrete input is a *string* therefore the process will convert the path string into a file :/

think it's a good opportunity to change all `file`  to `path` in the input and output definitions

**Comment by pditommaso** [comment]
> You got it. Only exception is process-per-file-chunk.nf, because it uses behavior of file to convert implicitly text into file chunks

Ok, that's fine to keep it as example why to use `file` instead of `path` 👍 

> One other question is, do you want to replace echo with debug

Yes, let's go with `debug`!

**Comment by bentsherman** [comment]
Ready to go 👍

**Pull request merged**
